# Copyright 2026 Chi Wai Chan
# See LICENSE file for licensing details.

[tox]
skipsdist = true
skip_missing_interpreters = true
envlist = lint, unit, static, coverage-report
requires = tox>=4.21
no_package = true

[testenv]
passenv =
    PYTHONPATH
    CHARM_BUILD_DIR
    MODEL_SETTINGS
runner = uv-venv-lock-runner
setenv =
    PYTHONPATH = {toxinidir}:{toxinidir}/lib:{[vars]src_path}
    PYTHONBREAKPOINT = ipdb.set_trace
    PY_COLORS = 1

[testenv:fmt]
description = Apply coding style standards to code
commands =
    ruff check --fix --select I {[vars]all_path}
    ruff format {[vars]all_path}
dependency_groups = fmt

[testenv:lint]
description = Check code against coding style standards
commands =
    codespell {toxinidir}
    ruff format --check --diff {[vars]all_path}
    ruff check {[vars]all_path}
    mypy {[vars]all_path}
dependency_groups = lint

[testenv:unit]
description = Run unit tests
commands =
    coverage run --source={[vars]src_path} -m pytest --ignore={[vars]tst_path}integration -v --tb native -s {posargs}
    coverage report
dependency_groups = unit

[testenv:coverage-report]
description = Create test coverage report
commands = coverage report
dependency_groups = coverage-report

[testenv:static]
description = Run static analysis tests
commands = bandit -c {toxinidir}/pyproject.toml -r {[vars]src_path} {[vars]tst_path}
dependency_groups = static

[testenv:integration]
description = Run integration tests
commands =
    pytest -v --tb native --ignore={[vars]tst_path}unit --log-cli-level=INFO -s {posargs}
dependency_groups = integration

[testenv:lint-fix]
description = Apply coding style standards to code
commands =
    ruff check --fix --fix-only {[vars]all_path}
dependency_groups = lint

[vars]
src_path = {toxinidir}/src/
tst_path = {toxinidir}/tests/
all_path = {toxinidir}/src/ {toxinidir}/tests/
