# Copyright 2026 Chi Wai Chan
# See LICENSE file for licensing details.

name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check:
    uses: ./.github/workflows/check.yaml
    secrets: inherit

  publish:
    name: Publish to edge
    needs: [check]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download charm artifact
        uses: actions/download-artifact@v4
        with:
          name: charm
          path: built-charm

      - name: List the names of the tested charms
        run: |
          echo "CHARM_NAMES=$(ls *.charm | paste -sd ,)" | tee -a "$GITHUB_ENV"

      - name: Upload charm to Charmhub
        uses: canonical/charming-actions/upload-charm@2.6.0
        with:
          channel: latest/edge
          credentials: ${{ secrets.CHARMHUB_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          built-charm-path: "${{ env.CHARM_NAMES }}"
